      var ubermenu_data = {
        remove_conflicts: "on",
        reposition_on_load: "off",
        intent_delay: "300",
        intent_interval: "100",
        intent_threshold: "7",
        scrollto_offset: "50",
        scrollto_duration: "1000",
        responsive_breakpoint: "959",
        accessible: "on",
        retractor_display_strategy: "responsive",
        touch_off_close: "on",
        submenu_indicator_close_mobile: "on",
        collapse_after_scroll: "on",
        v: "3.7.8",
        configurations: ["top_nav", "section_nav", "main"],
        ajax_url: "https:\/\/acad.org\/wp-admin\/admin-ajax.php",
        plugin_url: "https:\/\/acad.org\/wp-content\/plugins\/ubermenu\/",
        disable_mobile: "off",
        prefix_boost: "",
        use_core_svgs: "off",
        aria_role_navigation: "off",
        aria_nav_label: "off",
        aria_expanded: "off",
        aria_hidden: "off",
        aria_controls: "",
        aria_responsive_toggle: "off",
        icon_tag: "i",
        esc_close_mobile: "on",
        theme_locations: {
          "primary-menu": "Primary Menu",
          "top-menu": "Top Menu",
          shiftnav: "ShiftNav [Main]",
          "section-nav-menu": "Section Nav",
        },
      };
